name: 'Terraform Setup'
description: 'Setup Terraform environment with AWS credentials and state bucket verification'
inputs:
  aws-role-arn:
    description: 'AWS role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  environment:
    description: 'Environment name for role session'
    required: true
  state-bucket:
    description: 'S3 bucket for Terraform state'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: GitHubActions-${{ inputs.environment }}

    - name: Verify State Bucket Access
      shell: bash
      run: |
        echo "Verifying state bucket access..."
        aws s3 ls s3://${{ inputs.state-bucket }} || {
          echo "Error: Cannot access state bucket ${{ inputs.state-bucket }}"
          exit 1
        }